version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./database:/app/database
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./runs:/app/runs
      - ./database:/app/database
      - ./logo_branding_eye.png:/app/logo_branding_eye.png:ro
      - ./.streamlit:/root/.streamlit  # Añade esta línea
    depends_on:
      - api
    environment:
      - PYTHONPATH=/app/src
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - PYTHONUNBUFFERED=1
      - API_URL=http://api:8000


