version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./database:/app/database
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./runs:/app/runs
      - ./database:/app/database
      - ./logo_branding_eye.png:/app/logo_branding_eye.png
    depends_on:
      - api
    environment:
      - PYTHONUNBUFFERED=1


