[theme]
primaryColor="#6C63FF"
backgroundColor="#E6E6FA"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

[browser]
gatherUsageStats = false

[server]
enableXsrfProtection = false
enableCORS = false